### ISSUE TITLE
soynlp.normalizer의 repeat_normalize에 문제가 있는 것 같습니다.

### ISSUE THREAD

**Issue by seunghyukcho** [lovit/soynlp#108]
안녕하세요. `repeat_normalize`를 사용하던 중에 문제가 발생하여 문의드립니다.

다음 코드를 실행하면 원래 'ㅋㅋ'이 나와야 하지만, 'ㅋㅋㅋ'이 그대로 출력됩니다.

다른 글자들도 마찬가지입니다. 

```python
from soynlp.normalizer import *

repeat_normalize('ㅋㅋㅋ', num_repeats=2)  # ㅋㅋㅋ
repeat_normalize('ㅋㅋㅋㅋ', num_repeats=2)  # ㅋㅋ 
repeat_normalize('www', num_repeats=2)  # www
repeat_normalize('wwww', num_repeats=2) # ww
```

**Comment by lovit** [comment]
동읾일문제 확인하였습니다. 3글자 이하일 경우에 해당 문제가 발생하는 것으로 예상됩니다. 해당 문제 수정하겠습니다.

![image](https://user-images.githubusercontent.com/3401574/89969197-c236e400-dc90-11ea-93f5-278162494251.png)

**Comment by lovit** [comment]
해당 이슈 PR #109 을 통하여 해결하였습니다.

![image](https://user-images.githubusercontent.com/3401574/89969507-87817b80-dc91-11ea-97d0-ae0d2ca11b16.png)

현재 패키지 리펙토링을 계획하고 있어서 pypi 등록을 따로 하지는 않았습니다.
github 에서 git clone 하신 뒤 `python setup.py install` 로 설치해 주시기 바랍니다.

레포팅해주셔서 감사합니다.
