### ISSUE TITLE
[Question] 학습데이터에 대한 format

### ISSUE THREAD

**Issue by SHwan93** [lovit/soynlp#114]
해당 라이브러리를 사용하기위해 훈련과정이 우선적으로 작동되어야하는데

corpus_path에 해당하는 파일의 데이터 형식을 찾지 못하고 있는데 알려주실 수 있을까요?

예: txt의 줄바꿈으로 문장구분

**Comment by lovit** [comment]
포멧팅에 대한 이야기를 적지 않았었네요. 이후에 수정해두도록 하겠습니다.

텍스트 파일에서 한 줄이 하나의 문서라 가정합니다. 한 줄 내에서 두 칸 띄어쓰기를 문장의 구분자로 이용합니다. 아래와 같은 2문장, 1문장으로 이뤄진 데이터는 아래처럼 저장됩니다.

(concept)
```
[
  ['이것은 문장입니다', '두번째 문장입니다'],
  ['두번째 문서입니다'],
]
```

(corpus_path)
```
이것은 문장입니다  두번째 문장입니다
두번째 문서입니다
```

```python
from soynlp.utils import DoublespaceLineCorpus

corpus = DoublespaceLineCorpus(corpus_path, iter_sent=True)
len(corpus)  # 3

corpus.iter_sent = False
len(corpus)  # 2
```

혹은 DoublespaceLineCorpus 를 입력하는 모든 부분은 `list of str` 로 텍스트를 직접 로딩하셔서 입력하여도 괜찮습니다.

**Comment by SHwan93** [comment]
감사합니다~~
