### ISSUE TITLE
LRNounExtractor_v2가 어미를 잘 제거하지 못하는 문제가 있습니다.

### ISSUE THREAD

**Issue by burn001** [lovit/soynlp#12]
LRNounExtractor와 LRNounExtractor_v2에 의한 명사 추출 결과를 비교해 봤는데, 원래 버전(1.0)에서는 '하다', '하게', '하기', '하고', '하려' 등의 어미를 제거한 명사 part가 잘 추출되는 반면, v2에서는 어미가 붙어서 명사로 추출되는 경우가 다수 발견됩니다. 원래 의도대로 잘 구현된 것인지 검토가 필요한 듯 합니다.

**Comment by lovit** [comment]
LRNounExtractor 에서는 추출된 명사들에서 명사 + positive feature를 제거하는 후처리 기능이 있었습니다. 하지만 이 과정에서, 명사임에도 필터링이 되는 경우들이 발생하여 아직 v2 용 후처리 기능을 만들지 않았습니다. 알려주신 문제는 이것 때문으로 생각됩니다. 현재 v1 에서 이용하는 후처리 기능을 붙여두었습니다. 아직 pip install 로는 되지 않으며, git clone 을 하여 이용하실 수 있습니다. 더 정교한 후처리 함수는 이후에 추가하도록 하겠습니다.

**Comment by burn001** [comment]
수정된 코드를 사용해서 명사추출기를 훈련시켜보았습니다. 후처리기가 들어가니 조사나 어미가 붙어서 추출되는 경우가 현저히 감소하는 것을 확인할 수 있었습니다.

**Comment by burn001** [comment]
추가하신 후처리 함수에서 noun+pos_feature 인 경우 noun만 남기는 방식을 취하고 있는데, pos_feature만 추출된 경우는 후처리 함수를 통해 제거되지 않습니다. 그 결과, '으로', '에서'와 같이 pos_feature에 해당하는 단어가 명사로 추출되는 것으로 확인됩니다. 후처리 함수를 작성하실 때 참고하시면 좋을 것 같습니다.
