### ISSUE TITLE
soynlp Version 0.0.47 pip으로 설치시, import 에러

### ISSUE THREAD

**Issue by shuuki4** [lovit/soynlp#28]
PyPI에 올라와있는 Soynlp 버전 0.0.47을 pip으로 설치시, `import soynlp`에서 `FileNotFoundError`가 발생합니다.
```
FileNotFoundError: [Errno 2] No such file or directory: '/home/shuuki4/venv_tensorflow/lib/python3.5/site-packages/soynlp/noun/frequent_enrolled_josa.txt'
```
PyPI에 있는 0.0.47 버전 tar.gz 파일을 확인해보니, 해당 파일 자체가 누락되어 있는 것 같습니다.

**Comment by lovit** [comment]
setup.py 의 package_data 에 해당 파일을 포함하지 않았었네요. soynlp==0.0.48 에 해당 파일 포함하여 PyPI 에 등록하였습니다.
