### ISSUE TITLE
Noun Extractor  관련 질문입니다.

### ISSUE THREAD

**Issue by ysseo91** [lovit/soynlp#33]
안녕하세요. soynlp를 만들어주셔서 감사합니다.
초보 프로그래머라 질문 드립니다ㅜ

corpus_fname = 'YOUR_DoubleSpaceLine_Corpus'
sentences = DoublespaceLineCorpus(corpus_fname, iter_sent=True)
len(sentences)

이부분에서 'YOUR_DoubleSpaceLine_Corpus' 이부분이 이해가 가지 않습니다.
디렉토리 내에 있는 txt파일명을 넣어야 하는건지 
아니면 그 파일을 불러와서 list 형태로 만든 변수명을 넣어야하는건지...

감사합니다ㅜ

**Comment by lovit** [comment]
tutorials 폴더에 'doublespace_line_corpus_sample.txt' 파일이 있습니다.
해당 파일처럼 텍스트 파일을 만든 다음 파일 주소를 입력하면 됩니다.

DoublespaceLineCorpus 는 한 줄에 하나의 문서이며, 한 문서 내 줄바꿈 기호를 두 칸 띄어쓰기로 나눠둔 형식입니다. 

파일형식에 대한 내용은 tutorials/doublespace_line_corpus_(with_noun_extraction).ipynb 파일에 자세한 설명을 적어뒀습니다.
