### ISSUE TITLE
LRNounExtractor_v2 오류

### ISSUE THREAD

**Issue by karroo** [lovit/soynlp#37]
아래와 같은 에러가 발생하는 군요..

INFO] 2018-11-03 14:17:24.884     noun_data = noun_extractor.train_extract(text)
[INFO] 2018-11-03 14:17:24.884   File "/Users/ikarroo/anaconda3/envs/batch/lib/python3.6/site-packages/soynlp/noun/_noun_ver2.py", line 142, in train_extract
[INFO] 2018-11-03 14:17:24.884     self.train(sentences)
[INFO] 2018-11-03 14:17:24.884   File "/Users/ikarroo/anaconda3/envs/batch/lib/python3.6/site-packages/soynlp/noun/_noun_ver2.py", line 154, in train
[INFO] 2018-11-03 14:17:24.885     verbose=self.verbose)
[INFO] 2018-11-03 14:17:24.885   File "/Users/ikarroo/anaconda3/envs/batch/lib/python3.6/site-packages/soynlp/utils/utils.py", line 143, in__init__
[INFO] 2018-11-03 14:17:24.885     if sents:
[INFO] 2018-11-03 14:17:24.885   File "/Users/ikarroo/anaconda3/envs/batch/lib/python3.6/site-packages/pandas/core/generic.py", line 1576, in __nonzero__
[INFO] 2018-11-03 14:17:24.886     .format(self.__class__.__name__))
[INFO] 2018-11-03 14:17:24.886 ValueError: The truth value of a Series is ambiguous. Use a.empty, a.bool(), a.item(), a.any() or a.all().

**Comment by lovit** [comment]
코드 없이 에러 메시지만 본 상황이기 때문에 짐작이지만, pandas 의 Series 를 input 으로 넣으셔서 발생한 에러라 추측됩니다. 아래처럼 코드를 고쳐뒀지만, 제가 pandas Series 에 대해서 테스트를 해본 것은 아니기 때문에, 계속하여 동일한 오류가 발생한다면 list of str 이나 generator 형식으로 입력해주세요. 

(수정 전)

    if sents:
        ....

(수정 후)

    if sents is not None:
        ....

pypi 에는 아직 등록하지 않았으며, github 코드에만 수정부분을 올려두었습니다.
