### ISSUE TITLE
0.0.49버전에서 scipy import 에러

### ISSUE THREAD

**Issue by JeongUkJae** [lovit/soynlp#41]
`soynlp/word/_pmi.py`, `soynlp/vectorizer/_word_context.py`, `soynlp/vectorizer/_vectorizer.py`의 코드에 scipy를 import하는 것을 확인하였으나, `README.md`, `setup.py`에 추가되지 않아 있는 것으로 보아 누락되어 있는 것으로 보입니다.

**Comment by lovit** [comment]
커멘트 감사합니다. README 와 setup.py 에 scipy 를 추가하였습니다. 추가하였습니다.
