### ISSUE TITLE
soynlp 설치시 에러

### ISSUE THREAD

**Issue by shuuki4** [lovit/soynlp#83]
Commit bd0f8fb 기준입니다.

(1) `soynlp/word/_pmi.py` 에서 sklearn을 사용하고 있어 Require에 `sklearn`이 필요할것 같은데, sklearn이 없어서 `ModuleNotFoundError`가 발생합니다.
(2) `setup.py`의 `package_data`에 새로 추가된 dictionary 데이터인 `postagger/dictionary`가 포함되어 있지 않은 것 같습니다. 해당 데이터를 사용하는 코드에서 에러가 발생합니다.

**Comment by lovit** [comment]
(1) sklearn.metrics.pairwise_distances 만 이용하기 때문에 scikit-learn >= 0.20.0 이상으로 requirements 추가하였습니다. 
(2) 사전 파일을 자주 setup.py 에서 놓치네요. PredicatorExtractor 가 이용하는 사전 파일 추가하였습니다.
