### ISSUE TITLE
noun_extractor.train(sents)의 local error 문제

### ISSUE THREAD

**Issue by eomlocal** [lovit/soynlp#92]
명사추출 샘플실행시 "sents"에 대한 local error 문제가 발생합니다.
sents를 global로 지정해도 해결되지 않는데요, 어떻게 해결할 수 있나요
감사합니다.

noun_extractor = LRNounExtractor_v2(verbose = True)
nouns = noun_extractor.train(sents)

**>>unboundLocalError : local variable 'i_sent' referenced before assignment**

>>조치내용
global sents
nouns = noun_extractor.train(sents)

**Comment by eomlocal** [comment]
글쓴이 입니다. 해결했습니다!

**Comment by lovit** [comment]
확인해보니 sents 가 empty 이면 해당 문제가 발생하네요. 이 부분에 대해서는 조치해 두도록 하겠습니다. 알려주셔서 감사합니다.
