### ISSUE TITLE
BaseVectorizer to_file() 문제

### ISSUE THREAD

**Issue by km19809** [lovit/soynlp#99]
BaseVectorizer에서
```directory = os.path.dirname(file_path)
        if not os.path.exists(directory):
            os.makedirs(directory)
```

때문에 디렉토리 없는 파일을 넣으면 디렉토리 명이 없는 디렉토리를 만드려고 시도해 오류가 납니다.
이 부분 예외처리를 할 필요가 있어 보입니다.

**Comment by lovit** [comment]
문제를 알려주셔서 감사합니다. 해당 이슈는 #100 으로 해결하였습니다.
